# scripts/art_generator.py

import argparse
import os
import vertexai
from vertexai.preview.vision_models import ImageGenerationModel
from dotenv import load_dotenv
# NEW! It needs to talk to the Art Director now!
from art_director import refine_prompt_for_safety

# --- Configuration ---
load_dotenv()
# We can set how many times it's allowed to try again!
MAX_RETRIES = 3

def generate_image(project_id, location, prompt, output_path):
    """
    Generates an image using a Vertex AI Imagen model, with a retry loop.
    """
    print(f"🎨 Art Generator Bot v3.0 (Persistent Edition) activated! Engaging Vertex AI power core...")
    
    vertexai.init(project=project_id, location=location)
     # With our NEW, custom-trained, super-genius model ID!
    model = ImageGenerationModel.from_pretrained("YOUR_NEW_CUSTOM_MODEL_ID_GOES_HERE") 
    
    # We start with the original prompt
    current_prompt = prompt

    # --- THE GLORIOUS RETRY LOOP! ---
    for attempt in range(MAX_RETRIES):
        print(f"\n--- Generation Attempt {attempt + 1} of {MAX_RETRIES} ---")
        print(f"🤖 Model 'imagen-3.0-generate-002' locked and loaded.")
        print(f"📝 Using prompt: '{current_prompt}'")

        try:
            images = model.generate_images(
                prompt=current_prompt,
                number_of_images=1,
            )
            
            # If we get an image, it worked! SUCCESS!
            if images:
                print("✅ Image generated by the model! Saving to file...")
                images[0].save(location=output_path, include_generation_parameters=True)
                print(f"🎉 SUCCESS! The art-bot's creation is saved to: {output_path}")
                return # We're done! Exit the function!
            
            # If we get here, the image list was empty. Time to try again!
            print("⚠️ WARNING: The model returned no images. The prompt was likely rejected by safety filters.")
            if attempt < MAX_RETRIES - 1:
                # Ask the Art Director to make the prompt safer!
                current_prompt = refine_prompt_for_safety(current_prompt)
            
        except Exception as e:
            print(f"💥 DANGER! A critical meltdown occurred in the Vertex AI core!")
            print(f"Error details: {e}")
            break # If a real error happens, stop trying

    # If we finish the loop without success, we admit defeat.
    print(f"\n❌ FINAL FAILURE: Could not generate an image after {MAX_RETRIES} attempts.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generates an image from a text prompt using Vertex AI.")
    
    parser.add_argument("prompt", type=str, help="The text prompt to generate an image from.")
    parser.add_argument("output_path", type=str, help="The file path to save the generated PNG image.")
    args = parser.parse_args()

    project_id = os.getenv("GCP_PROJECT_ID")
    location = os.getenv("GOOGLE_CLOUD_LOCATION", "us-central1")

    output_dir = os.path.dirname(args.output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    generate_image(project_id, location, args.prompt, args.output_path)